#!/bin/bash

top_dir="../data/phys"

eos_dir="/eos/totem/data/ctpps/reconstruction/2017/preTS2_alignment_data/version1"

for f in `eos ls "$eos_dir"|grep ".root"`
do
	tag=${f%.*}

	fill=${tag%%_*}
	fill=${fill#fill}

	xangle=${tag#*_}
	xangle=${xangle%_*}
	xangle=${xangle#xangle}	

	stream=${tag##*_}

	# skip datasets for which there are no corresponding alignment data
	if [ "$xangle" -ne "120" -a "$xangle" -ne "130" -a "$xangle" -ne "140" -a "$xangle" -ne "150" ]
	then
		continue
	fi

	echo "* $fill, $xangle, $stream"

	# make work directory
	dir="$top_dir/fill_$fill/xangle_$xangle/$stream/"
	mkdir -p "$dir"

	# make config with input files
	(
		echo "import FWCore.ParameterSet.Config as cms"
		echo ""
		echo "input_files = cms.vstring("
		echo "    \"root://eostotem.cern.ch/${eos_dir}/${f}\""
		echo ")"
	) > "$dir/input_files.py"

	# if not present, make (default) config
	if [ ! -f "$dir/config.py" ]
	then
		cp "config_template.py" "$dir/config.py"
	fi
done
